### ISSUE TITLE
Wrong implementation ?

### ISSUE THREAD

**Issue by xvolte** [pfink/rfled-server-python#1]
Hello,

I have an issue with your python rfled server for milight.
First of all, i can start it without any issue (app recognize the milight bridge)
However, when i click on the button on the app, nothing happens.
I enabled the debug to print str(data) and i get the following letter printed when i click in the app:
H, I, J, K, L.

It appears that you then send to SERIAL directly the letter ? however, it is normally required to send packets like this : 
"B0 EE EA 04 91 03 45"

Could you please explain how to go from the letter received by your app, to write then the correct packet to serial ?

Thanks in advance,

**Comment by pfink** [comment]
Yes, input from the app is directly passed through to serial port. That's because the Milight protocol is damn simple, the original milight bridge does nothing more than this library does. You can find the protocol specification here: http://www.limitlessled.com/dev/

This library is tested for the v4.0 bridge hardware. If you would describe your complete setup (SBC, OS, used bridge hardware, ...), I could may help you.
